on: [push]

name: annoyance

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: clippy
        run: cargo clippy -- -D warnings
  
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: rustfmt
        run: cargo +nightly fmt --all -- --check
    
  cargo-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cargo-check
        run: cargo check --workspace --locked